name: Resuabale workflow

on:
  workflow_call:
    inputs:
        name:
            description: 'Input Description'
            type: string
            default: 'BIKI'
            required: false           
    secrets:        
        access-token:
            description: 'secret desrtition'
            required: true

jobs:
    checkout:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: ls -a
    log-context-and-inputs:
        runs-on: ubuntu-latest
        steps:
            - name: display github context
              run: echo '${{toJson(github)}}'
            - name: Display name input
              run: echo ${{ inputs.name }}
            - name: Display access-token secret
              run: echo ${{ secrets.access-token }}     
